### ISSUE TITLE
The RSS feed links are broken.

### ISSUE THREAD

**Issue by vedang** [isamert/isamert.github.io#2]
I tried the following links: 

- https://isamert.net/feed/main.xml
- https://isamert.net/feed/emacs.xml

Both give me the same error: 

```
XML Parsing Error: XML or text declaration not at start of entity
Location: https://isamert.net/feed/emacs.xml
Line Number 2, Column 1:
<?xml version="1.0" ?>
^
```

**Comment by isamert** [comment]
Whoops, thanks for pointing this out! I will fix it as soon as possible.
